logging:
  level:
    root: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework:
        transaction:
          interceptor: trace

spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
        hbm2ddl:
          auto: create
        highlight_sql: true
        auto_quote_keyword: true

decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      query:
        enable-logging: true
        log-level: DEBUG
        logger-name:
      slow-query:
        enable-logging: true
        log-level: WARN
        logger-name:
        threshold: 3
      multiline: true
      json-format: false
      count-query: false